highlights: pygments
safe: true
lsi: false
exclude: ['Gemfile', 'Gemfile.lock', 'app.yaml', 'README.md']
destination: _site
prose:
  rooturl: 'blog'
  siteurl: 'http://www.curiosityhacked.org'
  media: 'media'
  site: 'http://www.curiosityhacked.org/links.jsonp'
  metadata:
    blog:
    - name: "layout"
      field:
        element: "text"
        type: "text"
        help: "Currently blog or default"
        value: "blog"
